# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wfFv_Hb2LF6ieNBy0xBPAMXj5BQ-zs1_
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.plot(x, y, label="Sinus(x)", color="blue")

plt.title("Sinus Funksiyasining Grafigi")
plt.xlabel("X qiymatlari")
plt.ylabel("Y qiymatlari")

plt.grid(True)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

np.random.seed(42)
x = np.random.uniform(0, 10, 50)
y = np.random.uniform(0, 10, 50)

plt.figure(figsize=(8, 6))
plt.scatter(x, y, color='blue', label='Nuqtalar')

plt.title('Tasodifiy Nuqtalar Scatter Grafiki', fontsize=14)
plt.xlabel('X qiymatlari', fontsize=12)
plt.ylabel('Y qiymatlari', fontsize=12)
plt.legend()
plt.grid(True)
plt.show()

from PIL import Image
import matplotlib.pyplot as plt

file_paths = ["image1.jpg", "image2.jpeg", "image3.jpg"]

plt.figure(figsize=(15, 5))
for i, file_path in enumerate(file_paths):
    img = Image.open(file_path)

    img_gray = img.convert("L")

    plt.subplot(2, 3, i + 1)
    plt.imshow(img)
    plt.title(f"Original {i + 1}")
    plt.axis("off")

    plt.subplot(2, 3, i + 4)
    plt.imshow(img_gray, cmap="gray")
    plt.title(f"B&W {i + 1}")
    plt.axis("off")

plt.tight_layout()
plt.show()

import pandas as pd

file_path = 'WHO COVID-19 cases.csv'

df = pd.read_csv(file_path)
country_name = "Uzbekistan"
filtered_df = df[df['Country'] == country_name]
print(filtered_df.head())